// SPDX-License-Identifier: GPL-3.0-or-later

package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"
	"github.com/zclconf/go-cty/cty/function"
)

// Reading a list out of a file beside the document.
//
// # Why this exists
//
// Because the lists get long. `domains`, `start`, `included` and `excluded` are
// the four fields that grow to thousands of entries, and a seed list of three
// thousand URLs pasted into a job document is a document nobody can read, review
// or diff. They are also the four most likely to be generated by something else,
// or shared between jobs, or kept under their own review.
//
//	start   = lines("seeds.txt")
//	domains = lines("domains.txt")
//
// # Why it is read here and not when the crawl runs
//
// This is the part that matters, and it is the whole reason this file is short.
// A job document carries everything one crawl needs, so that a job resubmitted
// next month does what it did today. A function that read a file when the crawl
// ran would break that in the worst way available: the job's meaning would
// depend on a file on whichever machine happened to be running it, so the same
// job would crawl different sites on two nodes and nothing would say so.
//
// So the file is read once, where the document is, and the entries are expanded
// into the document before it is submitted. What the cluster stores is the list,
// not the reference. See [ExpandFiles].
//
// A document parsed without a directory to resolve against therefore refuses
// `lines` by name rather than guessing at a path. That is the case a node is in
// when it reads a stored job, and reading relative to a node's working
// directory is exactly the silent wrong answer this design is avoiding.
const linesFunc = "lines"

// linesFunction reads a list of entries from a file, resolved against dir.
//
// An empty dir means the document did not come from a file, so there is nothing
// to resolve against and the call is refused.
func linesFunction(dir string) function.Function {
	return function.New(&function.Spec{
		Params: []function.Parameter{{
			Name: "path",
			Type: cty.String,
		}},
		Type: function.StaticReturnType(cty.List(cty.String)),
		Impl: func(args []cty.Value, _ cty.Type) (cty.Value, error) {
			path := args[0].AsString()

			if dir == "" {
				return cty.NilVal, fmt.Errorf(
					"%s(%q) needs a document read from a file, and this one was not. "+
						"A job stored in a cluster carries its lists rather than a reference to them",
					linesFunc, path)
			}
			if !filepath.IsAbs(path) {
				path = filepath.Join(dir, path)
			}

			src, err := os.ReadFile(path)
			if err != nil {
				return cty.NilVal, fmt.Errorf("%s: %w", linesFunc, err)
			}

			entries := Lines(src)
			if len(entries) == 0 {
				// An empty list is a real answer and not an error: whether the
				// field may be empty is [Document.Validate]'s to say, and it
				// says it in the same words whether the list was written out or
				// read in.
				return cty.ListValEmpty(cty.String), nil
			}

			values := make([]cty.Value, 0, len(entries))
			for _, entry := range entries {
				values = append(values, cty.StringVal(entry))
			}
			return cty.ListVal(values), nil
		},
	})
}

// Lines is the entries a list file holds.
//
// One per line, with blank lines and `#` comments skipped and surrounding
// whitespace trimmed. That is what a list of domains or seed URLs looks like
// when a person or a script writes one, and the comments are the reason the
// format is not just "split on newlines": a seed list somebody maintains has
// notes in it saying why a URL is there.
//
// Exported because the expansion checks its work against it.
func Lines(src []byte) []string {
	var out []string
	for line := range strings.SplitSeq(string(src), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out
}

// ExpandFiles rewrites every `lines(...)` call into the list it reads.
//
// This is what keeps a job self-contained. The document an author writes may
// refer to a file beside it; the document a cluster stores may not, because
// nothing on the far side can see that file and a job's meaning must not depend
// on which machine is holding it. So the reference is resolved once, here,
// before the document is submitted.
//
// Only the attributes that use the function are touched. The rest of the file
// is returned byte for byte, comments, spacing and all, because what a client
// submitted is what a later reader should see and the diff between two
// submissions is the whole of what a resubmission is reviewed by. Reformatting
// somebody's document on the way through would make that diff unreadable.
//
// A document that does not use the function is returned unchanged, so this is
// safe to call on the way to every submission rather than only when somebody
// remembers to.
func ExpandFiles(src []byte, filename, dir string) ([]byte, error) {
	file, diags := hclwrite.ParseConfig(src, filename, hcl.InitialPos)
	if diags.HasErrors() {
		return nil, diagError(diags)
	}

	expanded, err := expandBody(file.Body(), filename, dir)
	if err != nil {
		return nil, err
	}
	if !expanded {
		// Byte for byte, rather than hclwrite's rendering of a file it did not
		// change. They are usually the same and "usually" is not good enough
		// for something every submission passes through.
		return src, nil
	}
	return file.Bytes(), nil
}

// expandBody rewrites one body and everything nested in it, reporting whether
// anything changed.
func expandBody(body *hclwrite.Body, filename, dir string) (bool, error) {
	var expanded bool

	for name, attr := range body.Attributes() {
		tokens := attr.Expr().BuildTokens(nil)
		if !calls(tokens, linesFunc) {
			continue
		}

		value, err := evaluate(tokens.Bytes(), filename, dir)
		if err != nil {
			return false, fmt.Errorf("%s: %w", name, err)
		}
		body.SetAttributeValue(name, value)
		expanded = true
	}

	// Sorted by nothing in particular: the blocks are rewritten in place and
	// the order they are visited cannot change the result.
	for _, block := range body.Blocks() {
		nested, err := expandBody(block.Body(), filename, dir)
		if err != nil {
			return false, err
		}
		expanded = expanded || nested
	}
	return expanded, nil
}

// calls reports whether an expression mentions a function by name.
//
// A token scan rather than a parse, because this runs over every attribute of
// every document submitted and the answer is no for almost all of them. What it
// costs to be wrong is nothing: a false positive is parsed and evaluated below,
// and an expression that turns out not to need expanding evaluates to what it
// already was.
func calls(tokens hclwrite.Tokens, name string) bool {
	for i, token := range tokens {
		if token.Type != hclsyntax.TokenIdent || string(token.Bytes) != name {
			continue
		}
		if i+1 < len(tokens) && tokens[i+1].Type == hclsyntax.TokenOParen {
			return true
		}
	}
	return false
}

// evaluate resolves one expression against the vocabulary.
func evaluate(src []byte, filename, dir string) (cty.Value, error) {
	expr, diags := hclsyntax.ParseExpression(src, filename, hcl.InitialPos)
	if diags.HasErrors() {
		return cty.NilVal, diagError(diags)
	}

	value, diags := expr.Value(evalContext(dir))
	if diags.HasErrors() {
		return cty.NilVal, diagError(diags)
	}
	return value, nil
}
