// SPDX-License-Identifier: GPL-3.0-or-later

package engine

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"
	"github.com/zclconf/go-cty/cty/function"
)

// Reading a list out of a file beside the document.
//
// # Why this exists
//
// Because the lists get long. `domains`, `start`, `included` and `excluded` are
// the four fields that grow to thousands of entries, and a seed list of three
// thousand URLs pasted into a job document is a document nobody can read, review
// or diff. They are also the four most likely to be generated by something else,
// or shared between jobs, or kept under their own review.
//
//	start   = lines("seeds.txt")
//	domains = lines("domains.txt")
//
// # Why it is read here and not when the crawl runs
//
// This is the part that matters, and it is the whole reason this file is short.
// A job document carries everything one crawl needs, so that a job resubmitted
// next month does what it did today. A function that read a file when the crawl
// ran would break that in the worst way available: the job's meaning would
// depend on a file on whichever machine happened to be running it, so the same
// job would crawl different sites on two nodes and nothing would say so.
//
// So the file is read once, where the document is, and the entries are expanded
// into the document before it is submitted. What the cluster stores is the list,
// not the reference. See [ExpandFiles].
//
// A document parsed without a directory to resolve against therefore refuses
// `lines` by name rather than guessing at a path. That is the case a node is in
// when it reads a stored job, and reading relative to a node's working
// directory is exactly the silent wrong answer this design is avoiding.
const linesFunc = "lines"

// linesFunction reads a list of entries from a file, resolved against dir.
//
// An empty dir means the document did not come from a file, so there is nothing
// to resolve against and the call is refused.
func linesFunction(dir string) function.Function {
	return function.New(&function.Spec{
		Params: []function.Parameter{{
			Name: "path",
			Type: cty.String,
		}},
		Type: function.StaticReturnType(cty.List(cty.String)),
		Impl: func(args []cty.Value, _ cty.Type) (cty.Value, error) {
			path := args[0].AsString()

			if dir == "" {
				return cty.NilVal, fmt.Errorf(
					"%s(%q) needs a document read from a file, and this one was not. "+
						"A job stored in a cluster carries its lists rather than a reference to them",
					linesFunc, path)
			}
			if !filepath.IsAbs(path) {
				path = filepath.Join(dir, path)
			}

			src, err := os.ReadFile(path)
			if err != nil {
				return cty.NilVal, fmt.Errorf("%s: %w", linesFunc, err)
			}

			entries := Lines(src)
			if len(entries) == 0 {
				// An empty list is a real answer and not an error: whether the
				// field may be empty is [Document.Validate]'s to say, and it
				// says it in the same words whether the list was written out or
				// read in.
				return cty.ListValEmpty(cty.String), nil
			}

			values := make([]cty.Value, 0, len(entries))
			for _, entry := range entries {
				values = append(values, cty.StringVal(entry))
			}
			return cty.ListVal(values), nil
		},
	})
}

// Lines is the entries a list file holds.
//
// One per line, with blank lines and `#` comments skipped and surrounding
// whitespace trimmed. That is what a list of domains or seed URLs looks like
// when a person or a script writes one, and the comments are the reason the
// format is not just "split on newlines": a seed list somebody maintains has
// notes in it saying why a URL is there.
//
// Exported because the expansion checks its work against it.
func Lines(src []byte) []string {
	var out []string
	for line := range strings.SplitSeq(string(src), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out
}

// ExpandFiles rewrites every `lines(...)` call into the list it reads.
//
// This is what keeps a job self-contained. The document an author writes may
// refer to a file beside it; the document a cluster stores may not, because
// nothing on the far side can see that file and a job's meaning must not depend
// on which machine is holding it. So the reference is resolved once, here,
// before the document is submitted.
//
// # Only the calls are replaced, and the replacement is spliced
//
// Everything else comes back byte for byte: the same indentation, the same
// comments, the same blank lines. That is a hard requirement rather than a
// nicety, and getting it wrong is not cosmetic.
//
// The first version of this rebuilt the document with hclwrite, whose Bytes
// reformats every token it holds. A document indented with four spaces came
// back indented with two, which changed the raw text of every plugin body, and
// plugin bodies are fingerprinted by exactly that text: [Job.snapshot] keeps
// the source of each block so that [Diff] can tell a configuration that changed
// from one that was merely moved. So expanding a list made `Diff` report that
// every plugin's config had changed, `effectOfPlugin` classified the cache
// plugin's as [EffectCacheMoved], and a job whose only edit was
// `domains = lines("domains.txt")` was refused on resubmission as though the
// operator had pointed the crawl at a different bucket.
//
// Splicing the expression's own byte range leaves everything it did not read
// exactly as it was, which is also what the diff between two submissions needs:
// the diff is the whole of what a resubmission is reviewed by.
//
// A document that does not use the function is returned unchanged, so this is
// safe to call on the way to every submission rather than only when somebody
// remembers to.
func ExpandFiles(src []byte, filename, dir string) ([]byte, error) {
	file, diags := hclsyntax.ParseConfig(src, filename, hcl.InitialPos)
	if diags.HasErrors() {
		return nil, diagError(diags)
	}

	body, ok := file.Body.(*hclsyntax.Body)
	if !ok {
		// Unreachable with this parser, and an assertion rather than a panic
		// because a wrong guess here would silently submit an unexpanded job.
		return nil, fmt.Errorf("%s: the document is not HCL syntax", filename)
	}

	var splices []splice
	if err := collect(body, src, dir, &splices); err != nil {
		return nil, err
	}
	if len(splices) == 0 {
		return src, nil
	}

	// Applied last-first, so an earlier splice's offsets are still the offsets
	// of the bytes it was measured against.
	sort.Slice(splices, func(i, j int) bool { return splices[i].start > splices[j].start })

	out := src
	for _, s := range splices {
		rewritten := make([]byte, 0, len(out)+len(s.with)-(s.end-s.start))
		rewritten = append(rewritten, out[:s.start]...)
		rewritten = append(rewritten, s.with...)
		rewritten = append(rewritten, out[s.end:]...)
		out = rewritten
	}
	return out, nil
}

// splice is one expression's byte range and what replaces it.
type splice struct {
	start, end int
	with       []byte
}

// collect finds every expression that reads a file, in one body and everything
// nested in it.
func collect(body *hclsyntax.Body, src []byte, dir string, into *[]splice) error {
	for name, attr := range body.Attributes {
		span := attr.Expr.Range()
		if !calls(src[span.Start.Byte:span.End.Byte], linesFunc) {
			continue
		}

		value, diags := attr.Expr.Value(evalContext(dir))
		if diags.HasErrors() {
			return fmt.Errorf("%s: %w", name, diagError(diags))
		}

		*into = append(*into, splice{
			start: span.Start.Byte,
			end:   span.End.Byte,
			with:  render(value, indentOf(src, attr.SrcRange.Start.Byte)),
		})
	}

	for _, block := range body.Blocks {
		if err := collect(block.Body, src, dir, into); err != nil {
			return err
		}
	}
	return nil
}

// calls reports whether an expression's source mentions a function by name.
//
// A scan of the expression's own bytes rather than a walk of its AST, because
// the answer is no for almost every attribute of almost every document and the
// cost of being wrong is nothing: a false positive is evaluated below and
// evaluates to what it already was.
func calls(src []byte, name string) bool {
	rest := src
	for {
		at := bytes.Index(rest, []byte(name))
		if at < 0 {
			return false
		}
		after := rest[at+len(name):]
		// A call, not a longer identifier that happens to start with it.
		before := byte(' ')
		if at > 0 {
			before = rest[at-1]
		}
		if !isWord(before) && len(bytes.TrimLeft(after, " \t")) > 0 &&
			bytes.TrimLeft(after, " \t")[0] == '(' {
			return true
		}
		rest = after
	}
}

func isWord(c byte) bool {
	return c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9'
}

// indentOf is the whitespace the line at an offset begins with.
func indentOf(src []byte, at int) string {
	start := bytes.LastIndexByte(src[:at], '\n') + 1
	line := src[start:at]
	return string(line[:len(line)-len(bytes.TrimLeft(line, " \t"))])
}

// render writes a list value as HCL.
//
// One entry per line once there are more than a handful, because these lists
// are the long ones by definition: the whole reason a document reads them from
// a file is that there are thousands, and thousands on one line is a diff
// nobody can review. Short lists stay inline, where a line break would be
// noise.
func render(value cty.Value, indent string) []byte {
	if value.IsNull() || !value.CanIterateElements() {
		return hclwrite.TokensForValue(value).Bytes()
	}

	entries := value.AsValueSlice()
	if len(entries) == 0 {
		return []byte("[]")
	}
	if len(entries) <= inlineEntries {
		return hclwrite.TokensForValue(value).Bytes()
	}

	var b bytes.Buffer
	b.WriteString("[\n")
	for _, entry := range entries {
		b.WriteString(indent)
		b.WriteString("  ")
		b.Write(hclwrite.TokensForValue(entry).Bytes())
		b.WriteString(",\n")
	}
	b.WriteString(indent)
	b.WriteString("]")
	return b.Bytes()
}

// inlineEntries is how many a list may hold before it is written one per line.
const inlineEntries = 3

// HCLString renders a Go string as an HCL quoted string.
//
// Not %q, which is Go's syntax and not HCL's. The two agree until a value
// contains `${` or `%{`, which HCL reads as the start of an interpolation: a
// selector induced from a page carrying an unrendered template attribute, say
// `meta[name="og:title-${id}"]`, went into somebody's job document as a %q
// literal and the document stopped parsing. Every later command on it then
// failed with a diagnostic about an unknown variable, naming nothing that would
// lead anybody back to the selector.
//
// Here rather than in each writer, because there are two - the labels document
// and the job document - and one of them had it right while the other did not.
func HCLString(value string) string {
	return string(hclwrite.TokensForValue(cty.StringVal(value)).Bytes())
}
