// SPDX-License-Identifier: GPL-3.0-or-later

package extract

import (
	"encoding/json"
	"sort"
	"strings"

	"golang.org/x/net/html"
)

// page is one parsed document, with the things every property wants read once
// rather than once per property.
//
// A job with twenty properties would otherwise walk the tree twenty times
// looking for the same meta elements.
type page struct {
	url  string
	root *html.Node

	// base is what the page said relative links are relative to, from its
	// <base href>. Empty when it said nothing, which is almost always.
	//
	// Kept apart from url because the two are different facts: url is where
	// this page came from and is what a value's provenance points at, and base
	// is what the document declares its links mean. Resolving against the
	// first when the second exists is not a near miss - it is a different
	// path, so every relative link on the page is fetched from somewhere the
	// site does not serve and the pages it meant to point at are never queued.
	base string

	// meta is what the page says about itself: Open Graph, Twitter cards,
	// ordinary named meta elements and HTTP-equiv ones, keyed by the name as
	// written.
	meta map[string]string

	// linked is every JSON-LD object on the page, flattened to one level of
	// string values.
	linked map[string]string

	// micro is every itemprop, keyed by the property name.
	micro map[string]string

	// text is the page's visible text, for the regexes.
	text string

	// hrefs is every link, in document order and unresolved.
	hrefs []string
}

func newPage(url string, root *html.Node) *page {
	p := &page{
		url:    url,
		root:   root,
		meta:   map[string]string{},
		linked: map[string]string{},
		micro:  map[string]string{},
	}
	p.walk(root)
	p.text = textOf(root)
	return p
}

// walk reads everything the semantic lookup needs in one pass.
func (p *page) walk(n *html.Node) {
	if n.Type == html.ElementNode {
		switch n.Data {
		case "meta":
			// name, property and http-equiv are three spellings of the same
			// idea, and pages use all three for the same fields.
			value := attr(n, "content")
			for _, key := range []string{"property", "name", "itemprop", "http-equiv"} {
				if got := attr(n, key); got != "" && value != "" {
					p.meta[strings.ToLower(got)] = value
				}
			}

		case "link":
			if rel := attr(n, "rel"); rel != "" {
				if href := attr(n, "href"); href != "" {
					p.meta["link:"+strings.ToLower(rel)] = href
				}
			}

		case "script":
			if strings.EqualFold(attr(n, "type"), "application/ld+json") {
				// Read from the child text nodes rather than through textOf,
				// which skips scripts on purpose: their contents are code
				// everywhere except here, where they are the page's own
				// description of itself.
				p.readLinkedData(raw(n))
			}

		case "a":
			if href := attr(n, "href"); href != "" {
				p.hrefs = append(p.hrefs, href)
			}

		case "base":
			// The first one only. HTML says a document has at most one and
			// that later ones are ignored, and a page with two is a page
			// somebody generated by accident rather than one meaning the
			// second.
			if p.base == "" {
				if href := attr(n, "href"); strings.TrimSpace(href) != "" {
					// Resolved against the page, because a base may itself be
					// relative: <base href="/blog/"> is legal and common.
					p.base = resolve(p.url, href)
				}
			}
		}

		if prop := attr(n, "itemprop"); prop != "" {
			// The first one that says anything, rather than the first one at
			// all. A page may carry an empty placeholder for a name and then
			// the filled element later - a template's slot and the hydrated
			// byline, or a masthead widget above the article - and keeping the
			// placeholder meant the page stated the value in microdata and
			// nothing could read it. Later non-empty values still do not
			// displace an earlier non-empty one: the first real answer wins.
			name := strings.ToLower(prop)
			if value := nodeValue(n); strings.TrimSpace(p.micro[name]) == "" {
				p.micro[name] = value
			}
		}
	}

	for child := n.FirstChild; child != nil; child = child.NextSibling {
		p.walk(child)
	}
}

// readLinkedData flattens JSON-LD to the string fields a property could match.
//
// Flattened rather than walked as a graph, because what a property wants is
// "the headline", and every shape a publisher writes puts it under that name
// somewhere. Arrays and nested objects are descended into; the first value for
// a name wins, because the outermost object is the page's own.
//
// # Why the traversal is level by level, with the names sorted
//
// Because the sentence above was not true of the code. It descended depth
// first, over Go map iteration, so a nested `name` was reached before a
// sibling at the top level and which of two colliding names won was random per
// run. An ordinary schema.org article has `publisher.name` and `author.name`,
// and a job asking for the author got the publisher on some runs and the author
// on others, from the same cached page, which is the one thing a cached corpus
// is supposed to make impossible.
//
// Sorting alone would have made it repeatable and still wrong. Level by level
// is what makes the outermost object win, which is what the rule says and what
// a publisher's own headline being at the top of their JSON-LD means.
func (p *page) readLinkedData(body string) {
	var parsed any
	if err := json.Unmarshal([]byte(strings.TrimSpace(body)), &parsed); err != nil {
		// Malformed JSON-LD is extremely common and never worth failing a page
		// over: it is one of four ways to find a value.
		return
	}
	p.flatten("", parsed)
}

func (p *page) flatten(prefix string, value any) {
	type named struct {
		name  string
		value any
	}

	// push adds one value to the next level, expanding an array in place so
	// that its elements stay at the depth the array was at: a list of authors
	// is not further from the top of the document than a single author.
	push := func(into []named, name string, value any) []named {
		list, ok := value.([]any)
		if !ok {
			return append(into, named{name, value})
		}
		for _, inner := range list {
			into = append(into, named{name, inner})
		}
		return into
	}

	level := push(nil, prefix, value)
	for len(level) > 0 {
		var next []named

		for _, it := range level {
			switch v := it.value.(type) {
			case map[string]any:
				names := make([]string, 0, len(v))
				for name := range v {
					names = append(names, name)
				}
				sort.Strings(names)
				for _, name := range names {
					next = push(next, name, v[name])
				}
			case string:
				p.remember(it.name, v)
			case float64:
				p.remember(it.name, trimFloat(v))
			case bool:
				if v {
					p.remember(it.name, "true")
				} else {
					p.remember(it.name, "false")
				}
			}
		}
		level = next
	}
}

func (p *page) remember(name, value string) {
	name = strings.ToLower(strings.TrimSpace(name))
	value = strings.TrimSpace(value)
	if name == "" || value == "" {
		return
	}
	if _, seen := p.linked[name]; !seen {
		p.linked[name] = value
	}
}

// links returns every href on the page, resolved and deduplicated, in document
// order.
//
// Resolution and scope are the scheduler's business; what this owes is the list
// as the page wrote it, made absolute so that whoever queues them does not have
// to know which page they were on.
func (p *page) links() []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(p.hrefs))

	for _, href := range p.hrefs {
		resolved := resolve(p.against(), href)
		if resolved == "" || seen[resolved] {
			continue
		}
		seen[resolved] = true
		out = append(out, resolved)
	}
	return out
}

// against is what a relative URL on this page is relative to: what the document
// declared, and where it came from otherwise.
func (p *page) against() string {
	if p.base != "" {
		return p.base
	}
	return p.url
}

// raw is an element's literal text, scripts included. The only caller is
// JSON-LD, which is the one script whose contents are data.
func raw(n *html.Node) string {
	var b strings.Builder
	for child := n.FirstChild; child != nil; child = child.NextSibling {
		if child.Type == html.TextNode {
			b.WriteString(child.Data)
		}
	}
	return b.String()
}

// attr returns an attribute's value.
func attr(n *html.Node, name string) string {
	for _, a := range n.Attr {
		if strings.EqualFold(a.Key, name) {
			return strings.TrimSpace(a.Val)
		}
	}
	return ""
}

// nodeValue is what an element means as a value.
//
// The attribute where one lives, if the element is one that keeps its value in
// an attribute, and its text otherwise. A `<time datetime="2026-08-05">` says
// August in its attribute and "yesterday" in its text, and the machine-readable
// one is the one worth having.
func nodeValue(n *html.Node) string {
	if n.Type != html.ElementNode {
		return strings.TrimSpace(textOf(n))
	}

	switch n.Data {
	case "meta":
		return attr(n, "content")
	case "time":
		if v := attr(n, "datetime"); v != "" {
			return v
		}
	case "a", "link", "area":
		if v := attr(n, "href"); v != "" {
			return v
		}
	case "img", "source", "iframe", "embed", "audio", "video", "script":
		if v := attr(n, "src"); v != "" {
			return v
		}
	case "input":
		if v := attr(n, "value"); v != "" {
			return v
		}
	case "data":
		if v := attr(n, "value"); v != "" {
			return v
		}
	case "abbr":
		if v := attr(n, "title"); v != "" {
			return v
		}
	}

	if v := attr(n, "content"); v != "" {
		return v
	}
	return strings.TrimSpace(textOf(n))
}

// textOf reduces a subtree to its text.
//
// Script and style are skipped: their contents are code, and a body that
// swallowed the analytics snippet is a body nobody can classify.
func textOf(n *html.Node) string {
	var b strings.Builder
	collect(&b, n)
	return b.String()
}

func collect(b *strings.Builder, n *html.Node) {
	if n.Type == html.TextNode {
		b.WriteString(n.Data)
		return
	}
	if n.Type == html.ElementNode {
		switch n.Data {
		case "script", "style", "noscript", "template":
			return
		}
	}
	for child := n.FirstChild; child != nil; child = child.NextSibling {
		collect(b, child)
		if child.Type == html.ElementNode && block(child.Data) {
			// Block elements end a line, or "one<div>two</div>" reads as
			// "onetwo" and every extracted body is a run-on sentence.
			b.WriteString("\n")
		}
	}
}

func block(tag string) bool {
	switch tag {
	case "p", "div", "br", "li", "tr", "section", "article", "header", "footer",
		"h1", "h2", "h3", "h4", "h5", "h6", "blockquote", "pre", "ul", "ol",
		"table", "figure", "figcaption", "main", "aside", "nav":
		return true
	}
	return false
}

// describe says what a node is, in the shape somebody would write it.
//
// "<h1 class=headline>" rather than a selector, because it reports what was
// found rather than what would find it again. The two are different claims and
// only the first one is knowable from one page.
func describe(n *html.Node) string {
	if n == nil {
		return ""
	}
	if n.Type != html.ElementNode {
		return "text"
	}

	var b strings.Builder
	b.WriteString("<")
	b.WriteString(n.Data)

	for _, key := range []string{"itemprop", "property", "name", "rel", "class", "id", "datetime", "type"} {
		if v := attr(n, key); v != "" {
			b.WriteString(" ")
			b.WriteString(key)
			b.WriteString("=")
			b.WriteString(truncate(v, 40))
			break
		}
	}
	b.WriteString(">")
	return b.String()
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

func trimFloat(v float64) string {
	s := strings.TrimRight(strings.TrimRight(formatFloat(v), "0"), ".")
	if s == "" || s == "-" {
		return "0"
	}
	return s
}
